Invoice
BacoFoods/menu pull request #2
Opened 2023-08-26 07:44 UTC by ingmpesca

adding new endpoint to retrieve an invoice using an invoiceID query parameter

2023-08-28 20:04 UTC, Mayistikar requested changes

2023-08-28 20:04 UTC, Mayistikar commented on cmd/main.go
> +		Invoice: 	  *invoiceRoutes,
Las rutas del invoice no requiere un puntero, al cambiarlo probablemente va a necesitar cambiar la firma

2023-08-28 20:04 UTC, Mayistikar commented on cmd/tmp/build-errors.log
> +exit status 2exit status 2exit status 2exit status 2exit status 2exit status 2
Este archivo no debe versionarse

2023-08-28 20:04 UTC, Mayistikar commented on pkg/invoice/service.go
> +	//invoice Repository
No dejar código comentado

2023-08-28 21:22 UTC, ingmpesca commented on cmd/main.go
> +		Invoice: 	  *invoiceRoutes,
done ya quedó ajustado

2023-08-28 21:22 UTC, ingmpesca commented on cmd/tmp/build-errors.log
> +exit status 2exit status 2exit status 2exit status 2exit status 2exit status 2
R master, entendido.

2023-08-28 21:22 UTC, ingmpesca commented on pkg/invoice/service.go
> +	//invoice Repository
Ajustado, y me lo llevo para pulir esos detalles para próximas ocasiones. Gracias por el feedback.

2023-08-29 14:18 UTC, Mayistikar approved these changes

2023-08-29 14:18 UTC, merged