Feat/invoice update
BacoFoods/menu pull request #3
Opened 2023-08-31 02:48 UTC by ingmpesca

<img width="1393" alt="Captura de pantalla 2023-08-30 a la(s) 9 43 39 p m" src="https://github.com/BacoFoods/menu/assets/77132656/378b5ef5-38d1-4db5-ad4c-4a3d78411dc7">

endpoint that updates an invoice receiving as param the invoiceID and receives a body with the information of Type, PaymentID, SurchargeID, Tips and DiscountID.

2023-08-31 16:26 UTC, Mayistikar requested changes

2023-08-31 16:26 UTC, Mayistikar commented on pkg/invoice/handler.go
> +	updatedData := make(map[string]interface{})
update data no debería ser un map[string]any... lo mejor aquí es que desde el DTO RequestUpdateInvoice cree un método "ToInvoice" que le permita hacer esta transformación agregando las reglas de negocio que determine pertinente y pasar un puntero de tipo Invoice al service para que el service ya pueda trabajar con un objeto de dominio.

Una forma de hacerlo agregando reglas de negocio es usando el patrón de diseño builder sobre la entidad de dominio Invoice y que este builder construya una instancia de Invoice a partir del mapeo, como lo hace de las lineas 82 a 94 agregando las reglas de negocio que requiera.

2023-08-31 16:26 UTC, Mayistikar commented on pkg/invoice/service.go
> +	Update(invoiceID string, updateData map[string]interface{}) (*Invoice, error)
La firma debería recibir en su método Update un puntero tipo Invoice:

Update(invoice *Invoice) (*Invoice, error)

2023-08-31 16:26 UTC, Mayistikar commented on pkg/invoice/service.go
> +	for field, value := range updateData {
Este mapeo lo hace el ORM, revise otros updates en el proyecto.

2023-09-01 22:20 UTC, ingmpesca commented on pkg/invoice/handler.go
> +	updatedData := make(map[string]interface{})
Se implementa el patrón de diseño builder en "Builder.go"

2023-09-01 22:21 UTC, ingmpesca commented on pkg/invoice/service.go
> +	for field, value := range updateData {
Se refactoriza en service

2023-09-01 22:21 UTC, ingmpesca commented on pkg/invoice/service.go
> +	Update(invoiceID string, updateData map[string]interface{}) (*Invoice, error)
Se modifica la firma --> Update(invoice *Invoice) (*Invoice, error)

2023-09-06 14:26 UTC, Mayistikar requested changes

2023-09-06 14:26 UTC, Mayistikar commented on pkg/invoice/handler.go
> +
igual aqui el espacio

2023-09-20 19:45 UTC, closed without merging